---
name: Deploy Apps 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "12 3 * * *"

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SHINYAPPSIO_ACCOUNT: vedha-viyash
  APP_PREFIX: NEST

jobs:
  deploy:
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio:latest
    if: >
      !contains(github.event.commits[0].message, '[skip deploy]')
    strategy:
      fail-fast: false
      matrix:
        directory:
          - basic-teal
        channel:
          - dev
    steps:
      - name: Set channel related constants
        run: |
          echo "BRANCH_NAME=main" >> $GITHUB_ENV

      - name: Setup job token 🔑
        id: github-token
        run: |
          if [ "${{ secrets.REPO_GITHUB_TOKEN }}" == "" ]; then
            echo "REPO_GITHUB_TOKEN is empty. Substituting it with GITHUB_TOKEN."
            echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "Using REPO_GITHUB_TOKEN."
            echo "token=${{ secrets.REPO_GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Checkout repo 🛎
        uses: actions/checkout@v4
        with:
          ref: "${{ env.BRANCH_NAME }}"
          token: "${{ steps.github-token.outputs.token }}"

      - name: Add safe directory in git config
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Check if Cypress tests exist
        id: find-cypress
        run: |
          if [ -d ${{ matrix.directory }}/tests/cypress ]; then
            echo "has-cypress-tests=true" >> $GITHUB_OUTPUT
          else
            echo "Skipping frontend tests because cypress directory does not exist."
            echo "has-cypress-tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Install additional system dependencies
        run: |
          apt-get update
          apt-get install --yes \
            libgtk2.0-0 \
            libgbm-dev \
            libnotify-dev \
            libgconf-2-4 \
            xvfb
          if [ " ${{ matrix.directory }}" == "python" ]
          then {
            apt-get install --yes python3.10-venv
          }
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        if: steps.find-cypress.outputs.has-cypress-tests == 'true'
        with:
          node-version: 20

      - name: Restore renv from cache
        uses: actions/cache@v3
        env:
          CACHE_KEY: renv-${{ runner.arch }}-${{ runner.os }}-${{ matrix.directory }}-${{ matrix.channel }}
        with:
          path: ${{ matrix.directory }}/renv/library
          key: ${{ env.CACHE_KEY }}-${{ hashFiles(format('{0}/renv.lock', matrix.directory)) }}
          restore-keys: ${{ env.CACHE_KEY }}-

      - name: Update renv.lock file with updated GitHub packages
        shell: Rscript {0}
        run: |
          setwd("${{ matrix.directory }}")
          lockfile <- renv::lockfile_read()
          pkg_name_structure <- ifelse("${{ matrix.channel }}" == "stable", "%s/%s@*release", "%s/%s")
          for (package in lockfile$Packages) {
              if (package$Source == "GitHub") {
                  # TODO: After teal.slice is released we have to remove this change.
                  # This workaround is because update to {bslib} breaks current release of teal.slice
                  if (package$Package == "teal.slice" && "${{ matrix.channel }}" == "stable") {
                    renv::record("insightsengineering/teal.slice@103491c67e26a9a85d636bd105a806904a0111ec")
                  } else {
                    renv::record(sprintf(pkg_name_structure, package$RemoteUsername, package$Package))
                  }
              }
          }

      - name: Install R packages using renv and update the renv snapshot
        shell: Rscript {0}
        working-directory: ${{ matrix.directory }}
        run: |
          options(renv.config.cache.symlinks = FALSE)
          lockfile_pkgs <- renv::lockfile_read()$Package
          github_pkgs <- names(lockfile_pkgs)[sapply(lockfile_pkgs, function(x) x$Source == "GitHub")]
          renv::restore(clean = TRUE)
          renv::update(exclude = github_pkgs)
          renv::snapshot()

      - name: Print the new renv.lock file for ${{ matrix.directory }}
        working-directory: ${{ matrix.directory }}
        run: cat renv.lock

      - name: Front end test to check if the app works fine
        if: steps.find-cypress.outputs.has-cypress-tests == 'true'
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          build: npm install cypress --save-dev
          working-directory: ${{ matrix.directory }}/tests
          start: npm run run-app
          wait-on: "http://localhost:3333"
          wait-on-timeout: 500

      - name: Install deployment-related R package dependencies
        shell: Rscript {0}
        working-directory: ${{ matrix.directory }}
        run: |
          install.packages(c("BiocManager", "connectapi"))
          renv::install("rsconnect@0.8.29")

      - name: Deploy 🖨 ${{ matrix.directory }} 🎨
        shell: Rscript {0}
        continue-on-error: true
        working-directory: ${{ matrix.directory }}
        run: |
          deploy_files <- c("app.R", "renv.lock", "renv/activate.R")
          rsconnect::writeManifest(".", deploy_files)
          rsconnect::connectApiUser(
            account = "vedha",
            server = "connect.appsilon.com",
            apiKey = "${{ secrets.CONNECT_API_KEY }}"
          )
          rsconnect::deployApp(
            ".",
            account = "vedha",
            appName = "remote-test",
            appTitle = "remote-test"
          )
